    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.DocumentoVendita', 'it.fornacecalandra.thip.vendite.documentoVE.YDocumentoVendita', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.DocumentoVenditaTM', 'it.fornacecalandra.thip.vendite.documentoVE.YDocumentoVenditaTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('DocumentoVendita', 'YDocumentoVendita', '1', 'Y');
